/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LaporanJurnalFrame.java
 *
 * Created on Aug 26, 2014, 9:16:34 PM
 */
package com.ivanbiz.ui;

import com.ivanbiz.dao.GLAccountDAO;
import com.ivanbiz.dao.JurnalDAO;
import com.ivanbiz.dao.impl.GLAccountDAOImpl;
import com.ivanbiz.dao.impl.JurnalDAOImpl;
import com.ivanbiz.model.GLAccount;
import com.ivanbiz.model.Jurnal;
import com.ivanbiz.service.ServiceHelper;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shbt Peterpan
 */
public class BiayaLainReportDialog extends javax.swing.JDialog {

    List<Jurnal> listJurnal;
    SimpleDateFormat dateFormat;
    SimpleDateFormat dateFormat1;
    NumberFormat numberFormat;
    GLAccountDAO gLAccountDAO;
    List<GLAccount> listGLAccounts;
    JurnalDAO jurnalDAO;

    public BiayaLainReportDialog(Date dari, Date sampai) {
        try {
            initComponents();
            dateFormat1 = new SimpleDateFormat("dd-MMMM-yyyy");
            jLabelJudul.setText("Dari tanggal " + dateFormat1.format(dari) + " sampai tanggal " + dateFormat1.format(sampai));
            numberFormat = NumberFormat.getNumberInstance();
            dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            gLAccountDAO = new GLAccountDAOImpl();
            jurnalDAO = new JurnalDAOImpl();
            listGLAccounts = gLAccountDAO.getDataByEquals(GLAccount.class, "groupACC", "BiayaLain");
            listJurnal = new ArrayList();
            for (GLAccount gLAccount : listGLAccounts) {
                Jurnal jurnal = new Jurnal();
                jurnal.setTransactionReference(gLAccount.getNameGL());
                jurnal.setGLAccount(gLAccount.getNoGL());
                jurnal.setCredit(jurnalDAO.getSumCreditGLAccount(dateFormat.format(dari), dateFormat.format(sampai), gLAccount.getNoGL()));
                listJurnal.add(jurnal);
            }
            updateTableJurnal(listJurnal);
        } catch (Exception ex) {
            Logger.getLogger(BiayaLainReportDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJurnal = new javax.swing.JTable();

        setAlwaysOnTop(true);
        setModal(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setText("Laporan Keuntugan Biaya Lain - Lain");

        jLabelJudul.setText("Dari Tanggal {} Sampai {}");

        tableJurnal.setAutoCreateRowSorter(true);
        tableJurnal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableJurnal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jLabelJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-808)/2, (screenSize.height-627)/2, 808, 627);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJurnal;
    // End of variables declaration//GEN-END:variables

    private void updateTableJurnal(List<Jurnal> listJurnal) {
        String[] judul = {"No", "No GL", "Nama GL", "Jumlah"};
        Object[][] isi = new Object[listJurnal.size()][4];
        int x = 0;
        int no = 0;
        for (Jurnal jurnal : listJurnal) {
            no += 1;
            isi[x][0] = no;
            isi[x][1] = jurnal.getGLAccount();
            isi[x][2] = jurnal.getTransactionReference();
            isi[x][3] = numberFormat.format(jurnal.getCredit());
            x++;
        }
        new ServiceHelper().setAutoRize(isi, judul, tableJurnal);
    }
}
